import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Apple,
  Bath,
  Bed,
  Bell,
  BookOpen,
  Briefcase,
  Camera,
  Candy,
  Check,
  CircleHelp,
  Clock,
  Cloud,
  CloudRain,
  Coffee,
  Cookie,
  Delete,
  Ear,
  Eye,
  FileText,
  Flag,
  Gamepad2,
  Gauge,
  Globe,
  Handshake,
  Heart,
  Home,
  Hospital,
  IceCreamCone,
  ImageIcon,
  Info,
  MessageCircle,
  Mic,
  Milk,
  Moon,
  MoonStar,
  Music,
  Octagon,
  PenSquare,
  Pencil,
  Pizza,
  Play,
  Plus,
  Rocket,
  Sandwich,
  School,
  Search,
  Settings,
  SlidersHorizontal,
  Smile,
  Snowflake,
  Soup,
  Sparkles,
  Star,
  Store,
  Sun,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Trees,
  Turtle,
  Tv,
  Type,
  Upload,
  Users,
  UtensilsCrossed,
  Volume2,
  Waves,
  X,
  Zap,
} from "lucide-react";

export const APP_ICONS = {
  "activity": Activity,
  "apple": Apple,
  "bath": Bath,
  "bed": Bed,
  "bell": Bell,
  "book-open": BookOpen,
  "briefcase": Briefcase,
  "camera": Camera,
  "candy": Candy,
  "check": Check,
  "circle-help": CircleHelp,
  "clock": Clock,
  "cloud": Cloud,
  "cloud-rain": CloudRain,
  "coffee": Coffee,
  "cookie": Cookie,
  "delete": Delete,
  "ear": Ear,
  "eye": Eye,
  "file-text": FileText,
  "flag": Flag,
  "gamepad-2": Gamepad2,
  "gauge": Gauge,
  "globe": Globe,
  "handshake": Handshake,
  "heart": Heart,
  "home": Home,
  "hospital": Hospital,
  "ice-cream-cone": IceCreamCone,
  "image-icon": ImageIcon,
  "info": Info,
  "message-circle": MessageCircle,
  "mic": Mic,
  "milk": Milk,
  "moon": Moon,
  "moon-star": MoonStar,
  "music": Music,
  "octagon": Octagon,
  "pen-square": PenSquare,
  "pencil": Pencil,
  "pizza": Pizza,
  "play": Play,
  "plus": Plus,
  "rocket": Rocket,
  "sandwich": Sandwich,
  "school": School,
  "search": Search,
  "settings": Settings,
  "sliders-horizontal": SlidersHorizontal,
  "smile": Smile,
  "snowflake": Snowflake,
  "soup": Soup,
  "sparkles": Sparkles,
  "star": Star,
  "store": Store,
  "sun": Sun,
  "thermometer": Thermometer,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  "trees": Trees,
  "turtle": Turtle,
  "tv": Tv,
  "type": Type,
  "upload": Upload,
  "users": Users,
  "utensils-crossed": UtensilsCrossed,
  "volume-2": Volume2,
  "waves": Waves,
  "x": X,
  "zap": Zap,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof APP_ICONS;

export interface IconOption {
  value: AppIconName;
  label: string;
  keywords: string[];
}

export const CUSTOM_TILE_ICON_OPTIONS: IconOption[] = [
  { value: "star", label: "Star", keywords: ["favorite"] },
  { value: "heart", label: "Heart", keywords: ["love"] },
  { value: "message-circle", label: "Speech Bubble", keywords: ["talk", "chat"] },
  { value: "users", label: "People", keywords: ["family", "group"] },
  { value: "home", label: "Home", keywords: ["house"] },
  { value: "school", label: "School", keywords: ["class"] },
  { value: "book-open", label: "Book", keywords: ["read", "study"] },
  { value: "mic", label: "Microphone", keywords: ["speak", "voice"] },
  { value: "volume-2", label: "Sound", keywords: ["listen", "audio"] },
  { value: "play", label: "Play", keywords: ["start"] },
  { value: "gamepad-2", label: "Game", keywords: ["fun", "play"] },
  { value: "music", label: "Music", keywords: ["song"] },
  { value: "camera", label: "Camera", keywords: ["photo", "picture"] },
  { value: "apple", label: "Apple", keywords: ["food", "fruit"] },
  { value: "pizza", label: "Pizza", keywords: ["food"] },
  { value: "milk", label: "Milk", keywords: ["drink"] },
  { value: "sandwich", label: "Sandwich", keywords: ["food"] },
  { value: "cookie", label: "Cookie", keywords: ["snack"] },
  { value: "ice-cream-cone", label: "Ice Cream", keywords: ["dessert"] },
  { value: "soup", label: "Soup", keywords: ["food"] },
  { value: "coffee", label: "Drink", keywords: ["beverage"] },
  { value: "utensils-crossed", label: "Meal", keywords: ["eat"] },
  { value: "bed", label: "Bed", keywords: ["sleep"] },
  { value: "bath", label: "Bathroom", keywords: ["wash"] },
  { value: "store", label: "Store", keywords: ["shop"] },
  { value: "hospital", label: "Hospital", keywords: ["doctor"] },
  { value: "trees", label: "Trees", keywords: ["outside", "park"] },
  { value: "waves", label: "Water", keywords: ["pool", "swim"] },
  { value: "thermometer", label: "Hot", keywords: ["warm"] },
  { value: "snowflake", label: "Cold", keywords: ["cool"] },
  { value: "sun", label: "Sunny", keywords: ["day"] },
  { value: "moon", label: "Night", keywords: ["sleep"] },
  { value: "cloud", label: "Cloudy", keywords: ["weather"] },
  { value: "cloud-rain", label: "Rainy", keywords: ["weather"] },
  { value: "turtle", label: "Slow", keywords: ["gentle"] },
  { value: "zap", label: "Fast", keywords: ["quick"] },
  { value: "check", label: "Yes", keywords: ["done", "confirm"] },
  { value: "x", label: "No", keywords: ["cancel"] },
  { value: "circle-help", label: "Help", keywords: ["question"] },
  { value: "rocket", label: "Go", keywords: ["move"] },
  { value: "thumbs-up", label: "Like", keywords: ["good"] },
  { value: "thumbs-down", label: "Dislike", keywords: ["bad"] },
  { value: "flag", label: "Done", keywords: ["finish"] },
  { value: "eye", label: "Look", keywords: ["watch"] },
  { value: "sparkles", label: "New", keywords: ["special"] },
  { value: "bell", label: "Alert", keywords: ["notice"] },
  { value: "clock", label: "Time", keywords: ["wait"] },
  { value: "pencil", label: "Write", keywords: ["draw"] },
  { value: "pen-square", label: "Edit", keywords: ["custom"] },
  { value: "briefcase", label: "Work", keywords: ["job"] },
  { value: "tv", label: "Watch", keywords: ["screen"] },
  { value: "ear", label: "Listen", keywords: ["hear"] },
  { value: "activity", label: "Action", keywords: ["move"] },
  { value: "smile", label: "Happy", keywords: ["feeling"] },
  { value: "globe", label: "World", keywords: ["language"] },
];

export function isRasterImageDataUrl(value: string) {
  return /^data:image\/(png|jpeg|gif|webp|bmp|avif);base64,/.test(value);
}

export function getAppIcon(value: string): LucideIcon | undefined {
  return APP_ICONS[value as AppIconName];
}

export function isAppIconName(value: string): value is AppIconName {
  return value in APP_ICONS;
}
