import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Apple,
  Bath,
  Bed,
  Bell,
  BookOpen,
  Briefcase,
  Camera,
  Candy,
  Check,
  CircleHelp,
  Clock,
  Cloud,
  CloudRain,
  Coffee,
  Cookie,
  Delete,
  Ear,
  Eye,
  FileText,
  Flag,
  Gamepad2,
  Gauge,
  Globe,
  Handshake,
  Heart,
  Home,
  Hospital,
  IceCreamCone,
  ImageIcon,
  Info,
  MessageCircle,
  Mic,
  Milk,
  Moon,
  MoonStar,
  Music,
  Octagon,
  PenSquare,
  Pencil,
  Pizza,
  Play,
  Plus,
  Rocket,
  Sandwich,
  School,
  Search,
  Settings,
  SlidersHorizontal,
  Smile,
  Snowflake,
  Soup,
  Sparkles,
  Star,
  Store,
  Sun,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Trees,
  Turtle,
  Tv,
  Type,
  Upload,
  Users,
  UtensilsCrossed,
  Volume2,
  Waves,
  X,
  Zap,
} from "lucide-react";

export const APP_ICONS = {
  "activity": Activity,
  "apple": Apple,
  "bath": Bath,
  "bed": Bed,
  "bell": Bell,
  "book-open": BookOpen,
  "briefcase": Briefcase,
  "camera": Camera,
  "candy": Candy,
  "check": Check,
  "circle-help": CircleHelp,
  "clock": Clock,
  "cloud": Cloud,
  "cloud-rain": CloudRain,
  "coffee": Coffee,
  "cookie": Cookie,
  "delete": Delete,
  "ear": Ear,
  "eye": Eye,
  "file-text": FileText,
  "flag": Flag,
  "gamepad-2": Gamepad2,
  "gauge": Gauge,
  "globe": Globe,
  "handshake": Handshake,
  "heart": Heart,
  "home": Home,
  "hospital": Hospital,
  "ice-cream-cone": IceCreamCone,
  "image-icon": ImageIcon,
  "info": Info,
  "message-circle": MessageCircle,
  "mic": Mic,
  "milk": Milk,
  "moon": Moon,
  "moon-star": MoonStar,
  "music": Music,
  "octagon": Octagon,
  "pen-square": PenSquare,
  "pencil": Pencil,
  "pizza": Pizza,
  "play": Play,
  "plus": Plus,
  "rocket": Rocket,
  "sandwich": Sandwich,
  "school": School,
  "search": Search,
  "settings": Settings,
  "sliders-horizontal": SlidersHorizontal,
  "smile": Smile,
  "snowflake": Snowflake,
  "soup": Soup,
  "sparkles": Sparkles,
  "star": Star,
  "store": Store,
  "sun": Sun,
  "thermometer": Thermometer,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  "trees": Trees,
  "turtle": Turtle,
  "tv": Tv,
  "type": Type,
  "upload": Upload,
  "users": Users,
  "utensils-crossed": UtensilsCrossed,
  "volume-2": Volume2,
  "waves": Waves,
  "x": X,
  "zap": Zap,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof APP_ICONS;
export type AppIconStyle = "outline" | "filled";

export interface IconOption {
  value: AppIconName;
  label: string;
  keywords: string[];
}
